# Generated by Django 4.1.7 on 2023-04-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedules',
            name='body',
        ),
        migrations.AlterField(
            model_name='schedules',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
